app/models.py
from flask import current_app, flash
from os.path import join as os_join_path
import re
from datetime import datetime, timedelta


class Log(object):
    def __init__(self, file_names, time_parse_format, log_line_pattern):
        self.file_names = file_names
        self.parse_time = lambda time: datetime.strptime(time, time_parse_format)
        self.time_parse_format = time_parse_format
        self.pattern = re.compile(log_line_pattern)
        self.load()

    def load(self):
        self.log_entries = []
        basedir = current_app.config['BASEDIR']
        for fname in self.file_names:
            for line in file(os_join_path(basedir, fname)):
                try:
                    processed = self.process_line(line)
                    self.log_entries.append(processed)
                except Exception as ex:
                    flash("Failed to process log line %r"%line, "error")
                    flash(ex, "error")

    def process_line(self, line):
        entry = self.pattern.match(line).groupdict()
        entry['time'] = self.parse_time(entry['logtime'])
        entry['timestamp'] = datetime.strftime(entry['time'], '%Y-%m-%d %H:%M:%S')
        return entry

    default_filters = {
        '-requesturi': (
            '^/static/(css|img|js)/',
            '^/favicon.ico$',
        ),
        'time': '5 days',
    }
    def entries(self, filters):
        log_entries = self.entries_filtered_by_time(
                                        filters.pop('time', '9999 days'),
                                        filters.pop('-time', '0 seconds'))
        for field, pattern in filters.iteritems(multi=True):
            pattern = re.compile(pattern)
            if field.startswith('-'):
                field = field[1:]
                test = lambda txt: not pattern.search(txt)
            else:
                test = lambda txt: pattern.search(txt)
            log_entries = [e for e in log_entries if test(e[field])]
        return log_entries

    def entries_filtered_by_time(self, not_before_pattern, not_after_pattern):
        log_entries = self.log_entries
        now = datetime.now()
        def to_threshold_datetime(delta_pattern):
            value, unit = re.match('^(\d+)\s*(\S+)$', delta_pattern).groups()
            return now - timedelta(**{str(unit): int(value)})
        not_before = to_threshold_datetime(not_before_pattern)
        not_after = to_threshold_datetime(not_after_pattern)
        log_entries = [e for e in log_entries
                       if not_before < e['time'] < not_after]
        return log_entries


logs = {}

def init():
    for handle, config in current_app.config['LOGS_TO_BROWSE'].items():
        logs[handle] = Log(**config)

app/__init__.py
#------------------------------------------------------------------------------#
# Imports
#------------------------------------------------------------------------------#
from flask import Flask
import logging
from logging import Formatter, FileHandler


def create_app(config_object_name='config'):
    app = Flask(__name__)
    app.config.from_object(config_object_name)

    from routes import blueprints
    for bp in blueprints:
        app.register_blueprint(bp)

    return app

app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask import current_app
from os.path import join as os_join_path
from collections import namedtuple
import apachelog
import re
import models

#------------------------------------------------------------------------------#
# Controllers
#------------------------------------------------------------------------------#

bp = Blueprint('logbrowser', __name__, template_folder='templates',
              static_folder='static', static_url_path='/static.logbrowser')
bp.before_app_first_request(models.init)
blueprints = [bp]

@bp.route("/")
def index():
    return render_template("logbrowser/index.html")

@bp.route("/<handle>")
@bp.route("/<handle>/raw", defaults={'use_default_filters': False})
def log_view(handle, use_default_filters=True):
    log = models.logs[handle]
    filters = request.args.copy()
    if use_default_filters:
        for k,val in log.default_filters.items():
            if isinstance(val, (str, unicode)):
                filters.add(k, val)
            else:
                for v in val:
                    filters.add(k, v)
    entries = log.entries(filters)
    return render_template("logbrowser/log_view.html", entries=entries, handle=handle)

@bp.route("/<handle>/refresh")
def refresh_log(handle):
    log = models.logs[handle]
    log.load()
    flash("Refreshed", "success")
    redirect_to = request.referrer or url_for('.log_view', handle=handle)
    return redirect(redirect_to)


# Error Handlers

@bp.app_errorhandler(500)
def internal_error(error):
    return render_template('logbrowser/500.html'), 500

@bp.route('/<path:invalid_path>')
def internal_error(invalid_path):
    return render_template('logbrowser/404.html'), 404

app/templates/log_view.html
{% extends "index.html" %}
{% block title %}{% endblock %}
{% block content %}
<table class="table table-plain">
    {% for entry in entries %}
    <tr style="color: hsl({{entry['agent'].__hash__()%359}}, {{50+entry['host'].__hash__()%50}}%, 50%);">
        <td class="td-time">{{entry['timestamp']}}</td>
        <td class="td-host" title="{{entry['agent']}}" data-toggle="tooltip">{{entry['host']}}</td>
        {% with tooltip="%s:%s - %s" % (entry['method'], entry['status'], entry['referer']) %}
        <td class="td-uri" title="{{tooltip}}" data-toggle="tooltip">{{entry['requesturi']}}</td>
        {% endwith %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block bottom_extra %}
<script>
$(document).ready(function() {
    $('td.td-host').tooltip({'placement': 'auto right', 'container': 'body'})
    $('td.td-uri').tooltip({'placement': 'auto left', 'container': 'body'})
});
</script>
{% endblock %}

{% block navbar_extra %}
<li><a href="{{url_for('.refresh_log', handle=handle)}}">Refresh</a></li>
{% endblock %}

app/templates/logbrowser/index.html
{% extends "logbrowser/template.html" %}
{% block title %} - Home{% endblock %}
{% block content %}
<h1>Welcome!</h1>
Please log in or register.
{% endblock %}

app/templates/logbrowser/log_view.html
{% extends "logbrowser/index.html" %}
{% block title %}{% endblock %}
{% block content %}
<table class="table table-plain">
    {% for entry in entries %}
    <tr style="color: hsl({{entry['agent'].__hash__()%359}}, {{50+entry['host'].__hash__()%50}}%, 50%);">
        <td class="td-time">{{entry['timestamp']}}</td>
        <td class="td-host" title="{{entry['agent']}}" data-toggle="tooltip">{{entry['host']}}</td>
        {% with tooltip="%s:%s - %s" % (entry['method'], entry['status'], entry['referer']) %}
        <td class="td-uri" title="{{tooltip}}" data-toggle="tooltip">{{entry['requesturi']}}</td>
        {% endwith %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block bottom_extra %}
<script>
$(document).ready(function() {
    $('td.td-host').tooltip({'placement': 'auto right', 'container': 'body'})
    $('td.td-uri').tooltip({'placement': 'auto left', 'container': 'body'})
});
</script>
{% endblock %}

{% block navbar_extra %}
<li><a href="{{url_for('.refresh_log', handle=handle)}}">Refresh</a></li>
{% endblock %}

app/templates/logbrowser/template.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Log Browser{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{url_for('.static',filename='css/bootstrap.css')}}">
        <script type=text/javascript>
          $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
    </head>
    <body>
        <!-- Static navbar -->
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('logbrowser.index')}}">Log Browser</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {%block navbar_extra%}{%endblock%}
                </ul>
            </div><!--/.nav-collapse -->
        </div>


        <div class="container">

            <div id="main" role="main">
                <div class="alert-messages">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-dismissable alert-{{category}} fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
                {% block content_no_row %}
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        {% block content %}{% endblock %}
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>

        <footer>
        {% block footer %}{% endblock %}
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<'+'script src="{{url_for('.static',filename='js/libs/jquery.min.js')}}"><\/script>')
        </script>
        <script defer src="{{url_for('.static',filename='js/libs/modernizr-2.0.6.min.js')}}"></script>
        <script defer src="{{url_for('.static',filename='js/libs/bootstrap.min.js')}}"></script>
        <script defer src="{{url_for('.static',filename='js/libs/bootstrap-datepicker.js')}}"></script>
        <script defer src="{{url_for('.static',filename='js/plugins.js')}}"></script>
        <script defer src="{{url_for('.static',filename='js/script.js')}}"></script>
        {% block bottom_extra %}{% endblock %}
    </body>

</html>

app/templates/template.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Log Browser{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
        <script type=text/javascript>
          $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
    </head>
    <body>
        <!-- Static navbar -->
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('.index')}}">Log Viewer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {%block navbar_extra%}{%endblock%}
                </ul>
            </div><!--/.nav-collapse -->
        </div>


        <div class="container">

            <div id="main" role="main">
                <div class="alert-messages">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-dismissable alert-{{category}} fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
                {% block content_no_row %}
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        {% block content %}{% endblock %}
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>

        <footer>
        {% block footer %}{% endblock %}
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<'+'script src="{{url_for('static',filename='js/libs/jquery.min.js')}}"><\/script>')
        </script>
        <script defer src="{{url_for('static',filename='js/libs/modernizr-2.0.6.min.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/libs/bootstrap.min.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/libs/bootstrap-datepicker.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/plugins.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/script.js')}}"></script>
        {% block bottom_extra %}{% endblock %}
    </body>

</html>